### ISSUE TITLE
On python 3.8, getting DeprecationWarnings from pyqt / pyqtgraph libs

### ISSUE THREAD

**Issue by EklipZgit** [highfestiva/finplot#31] opened 2020-09-13 23:25 UTC
```

....\Python38\lib\site-packages\finplot\__init__.py:2051: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  return pg.mkColor(color).lighter(f*100)

# and

....\Python38\lib\site-packages\pyqtgraph\ThreadsafeTimer.py:26: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.timer.start(timeout)

# and

....\Python38\lib\site-packages\pyqtgraph\widgets\GraphicsView.py:374: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  delta = Point(ev.pos() - QtCore.QPoint(*self.lastMousePos))

```
Looks like lastMousePos is x,y floats, but pyqtgraph / pyqt5 is expecting ints now, and python itself seems to be complaining, spamming the console as you mouse around charts. 
```
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    # do finplot stuff
```
isn't really a great workaround but it does work.

Full list of my modules:

```
Module | InstalledVersion | LatestAvailable
PyQt5 | 5.13.0 | 5.15.1
PyQt5-sip | 12.8.1 | 12.8.1
aiohttp | 3.6.2 | 4.0.0a1
aiohttp-proxy | 0.1.2 | 0.1.2
async-timeout | 3.0.1 | 4.0.0a2
attrs | 19.3.0 | 20.2.0
certifi | 2020.6.20 | 2020.6.20
chardet | 3.0.4 | 3.0.4
ciso8601 | 2.1.3 | 2.1.3
ddt | 1.4.1 | 1.4.1
discord.py | 1.4.1 | 1.4.1
finplot | 1.1.0 | 1.1.0
idna | 2.10 | 2.10
multidict | 4.7.6 | 4.7.6
multitasking | 0.0.9 | 0.0.9
numpy | 1.19.2 | 1.19.2
pandas | 1.1.2 | 1.1.2
pandas-market-calendars | 1.5.0 | 1.6.0
pip | 20.1.1 | 20.2.3
plotly | 4.10.0 | 4.10.0
pygame | 1.9.6 | 2.0.0.dev8
pyqtgraph | 0.11.0 | 0.11.0
python-dateutil | 2.8.1 | 2.8.1
pytz | 2020.1 | 2020.1
requests | 2.24.0 | 2.24.0
retrying | 1.3.3 | 1.3.3
robin-stocks | 1.2.0 | 1.5.1
setuptools | 47.1.0 | 50.3.0
six | 1.15.0 | 1.15.0
ta | 0.5.25 | 0.5.25
urllib3 | 1.25.9 | 1.25.10
websockets | 8.1 | 8.1
yarl | 1.4.2 | 1.5.1
yfinance | 0.1.54 | 0.1.54
```

**Comment by highfestiva** [comment] 2020-09-15 07:32
I need to bump my local py installation too, so will look into it when I have time.

**Comment by highfestiva** [comment] 2020-09-17 09:39
Bumped to 3.8.6rc1 (and lost heatmaps in the process), but could not reproduce your problems. I have the same lib versions as you. Could you check if 3.8.6 removes those warnings?

**Comment by highfestiva** [comment] 2020-09-17 10:14
I fixed 2/3 with https://github.com/highfestiva/finplot/commit/154cc8f5df6032666553ce605f239d938f445022. If I was able to reproduce the last bug, I believe it might be fixed on line [2012](https://github.com/highfestiva/finplot/blob/master/finplot/__init__.py#L2012).

**Comment by highfestiva** [comment] 2020-09-19 14:44
Can you still reproduce the bug with py3.8.6rc1?

**Comment by highfestiva** [comment] 2020-09-20 15:16
@EklipZgit ?

**Comment by EklipZgit** [comment] 2020-09-20 23:44
@highfestiva hey sorry. Haven't figured out how github notifications work yet, clearly. Let me poke at this in a moment. I'm relatively new to python and not super comfortable hot swapping python versions in a complex project, but I'll try to copy my project over, remove the console-de-spam workaround and see if its still reproing. Let me give it a shot in the next hour or two and get back to you.

I had a couple other questions that I might as well ask here rather than making issues:

1. I'm seeing some graphs (admittedly with large numbers of candles, eg 2 months of 1m data) have the candles vanish when zooming in on certain parts of the graph. Probably bad data somewhere, but curious if thats something you're aware of and what I should look for when I poke into it further?

2. Any good way to mark candle charts with float-precision X axis markers? Eg I want to overlay real-time trades on top of the chart, but right now i'm locked to 1 'dumb marker' (from your examples) per candle. Rather, if I made 3 trades at different prices during that single candle I'd like to be able to drop 3 markers at different 'times' on the x-axis and have them show up on the plot at finer-than-the-drawn-candle-resolution. I'm guessing its not possible with out-of-box finplot, and possibly not even possible with PyQT even if I tried to do hacky stuff and call private parts of your module? I see in most (all?) of your examples, the dataframe is indexed numerically instead of a time-based index, though I have no idea if a time-based index would enable what I'm hoping for.

**Comment by highfestiva** [comment] 2020-09-21 07:34
1. This is possibly related to a yfinance bug, so use '60m' instead of '1h' as a workaround (https://github.com/ranaroussi/yfinance/issues/125).

2. Yes, but the solution is wierd due to internal representation of data being index-based, and you need to use something called "standalone" data source:

````python
df = yfinance.download('TSLA', '2018-09-30', interval='60m')

ax = fplt.create_plot('Tesla rocks')
fplt.candlestick_ochl(df[['Open','Close','High','Low']])

x0 = len(df)-12
x = [x0-0.2, x0+0.1, x0+0.3] # use indices, not timestamps
y0 = df.Close.iloc[-12]
y = [y0+0.1, y0+2.7, y0+7.9]
ds = fplt._create_datasrc(ax, x, y)
ds.standalone = True # don't try to fit timestamps into previous plots
fplt.plot(ds, style='>', width=2)

fplt.show()
````

![image](https://user-images.githubusercontent.com/160303/93741709-35ffd100-fbed-11ea-830e-f38bae10fe6e.png)

----

The `single positional indexer is out-of-bounds` is fixed by constraining the crosshair (not released to pypi yet). The other one is probably related to the yfinance bug. I hope. :)

**Comment by EklipZgit** [comment] 2020-09-21 20:04
Interesting. I don't actually use the yFinance module, but I do download my 1h data with '1h' parameter from the YF api, rather than '60m' I believe. I'll have to look into that and get back to you tonight on whether 60m helps.

Thanks for that sample on adding those plot points, that should work perfectly and is actually much easier than I thought it would be. I would never have thought of floats as data indices like that, that is awesome that that works!

Where can I find the list of all 'styles' (like the '>' you're using there)? I'm guessing PyQT docs, but not sure if thats a finplot specific thing?

Also, is there a quick way to cut intelligently cut off the charts autoscale for abnormal data? Eg TSLA has a single 1h candle that has a low of 0 during after hours, which makes the graph look ridiculous any time that low is on the screen. I was just going to prefilter the data but that feels dishonest if there is a way to have finplot just ignore single data points that would otherwise affect the chart scale by >3x on their own or something, such that I could mouse over it and see the low is 0, but have the chart look relatively normal with the wick going off the chart?

**Comment by yamen** [comment] 2020-09-21 20:32
Got to look through code for the styles, but they are `-_.` for lines and
`^v><` for markers. Finplot translates these into relevant Qt components.

Re: 'bad data' you _must_ prefilter these out, it makes no sense for the
charting package to do that type of work. It would be dishonest of finplot
to show you anything other than what's in your dataframe, and in fact it
would drive you insane. Since you can customise the crosshair function you
could create this 'heads up' for yourself, or put a marker on screen etc.

**Comment by highfestiva** [comment] 2020-09-21 20:44
Yup, that's the problem then (tried it).

Styles are not very many, but `^ v > < o . + x s d p h star` and you can combine dots and lines like so `..--.-` to generate a kind of hatched pen.

Regarding cut-off yamen has a point, but you could also try something like this to skip scaling on the lows:

````python
fplt.candlestick_ochl(df[['Date','Open','Close','High','Low']], ax=ax)
ax.vb.datasrc.scale_cols = [1,2,3] # defaults to [3,4] (which refers to columns high and low, while [1,2,3] means open,close,high)
ax.vb.v_zoom_scale = 0.8 # normally uses 0.97, i.e. 3% margin; pad some more since we're skipping low wicks
````

(Also you could also try Ctrl+MWheel to adjust the vertical zoom scale as necessary too.)

**Comment by highfestiva** [comment] 2020-09-22 06:45
Original question resolved in py3.8.6.

**Closed by highfestiva** 2020-09-22 06:45 UTC
